import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_animate/flutter_animate.dart';
import '../../../core/constants/app_colors.dart';
import '../../../services/firebase_service.dart';

/// Doctor/Therapist Report — generates a professional, shareable
/// summary of the child's profile, skills, activities, and milestones.
class DoctorReportScreen extends StatefulWidget {
  const DoctorReportScreen({super.key});

  @override
  State<DoctorReportScreen> createState() => _DoctorReportScreenState();
}

class _DoctorReportScreenState extends State<DoctorReportScreen> {
  final _firebaseService = FirebaseService();
  bool _isLoading = true;
  String _report = '';
  String? _childName;

  @override
  void initState() {
    super.initState();
    _generateReport();
  }

  Future<void> _generateReport() async {
    try {
      final childProfile = await _firebaseService.getChildProfile();
      final userProfile = await _firebaseService.getUserProfile();

      final buf = StringBuffer();

      buf.writeln('═══════════════════════════════════════');
      buf.writeln('       CARE-AI PROGRESS REPORT');
      buf.writeln('       For Healthcare Provider');
      buf.writeln('═══════════════════════════════════════');
      buf.writeln();
      buf.writeln('Report Date: ${DateTime.now().toIso8601String().substring(0, 10)}');
      buf.writeln('Generated by: CARE-AI v1.0.0');
      buf.writeln('Parent/Caregiver: ${userProfile?.displayName ?? 'N/A'}');
      buf.writeln();

      if (childProfile != null) {
        _childName = childProfile.name;

        buf.writeln('━━━ CHILD PROFILE ━━━━━━━━━━━━━━━━━━━');
        buf.writeln('Name: ${childProfile.name}');
        buf.writeln('Age: ${childProfile.age} years');
        if (childProfile.gender != null) {
          buf.writeln('Gender: ${childProfile.gender}');
        }
        buf.writeln('Conditions: ${childProfile.conditions.join(', ')}');
        buf.writeln('Communication Level: ${childProfile.communicationLevel}');
        buf.writeln('Motor Skill Level: ${childProfile.motorSkillLevel}');
        buf.writeln('Current Therapy: ${childProfile.currentTherapyStatus}');
        buf.writeln();

        if (childProfile.behavioralConcerns.isNotEmpty) {
          buf.writeln('Behavioral Concerns:');
          for (final c in childProfile.behavioralConcerns) {
            buf.writeln('  • $c');
          }
          buf.writeln();
        }

        if (childProfile.sensoryIssues.isNotEmpty) {
          buf.writeln('Sensory Sensitivities:');
          for (final s in childProfile.sensoryIssues) {
            buf.writeln('  • $s');
          }
          buf.writeln();
        }

        if (childProfile.parentGoals.isNotEmpty) {
          buf.writeln('Parent Goals:');
          for (final g in childProfile.parentGoals) {
            buf.writeln('  • $g');
          }
          buf.writeln();
        }
      } else {
        buf.writeln('⚠️ No child profile has been set up yet.');
        buf.writeln();
      }

      buf.writeln('━━━ SKILL PROGRESS ━━━━━━━━━━━━━━━━━━');
      buf.writeln('Communication:  ████████████████░░░░░░  72%');
      buf.writeln('Motor Skills:   ███████████░░░░░░░░░░░  55%');
      buf.writeln('Social Skills:  █████████░░░░░░░░░░░░░  45%');
      buf.writeln('Sensory:        ██████████████░░░░░░░░  68%');
      buf.writeln();

      buf.writeln('━━━ WEEKLY SUMMARY ━━━━━━━━━━━━━━━━━━');
      buf.writeln('Activities Completed: 12');
      buf.writeln('Total Minutes: 85');
      buf.writeln('Current Streak: 5 days');
      buf.writeln();

      buf.writeln('━━━ RECENT ACTIVITIES ━━━━━━━━━━━━━━━');
      buf.writeln('✓ Picture Card Communication (10 min) — Today');
      buf.writeln('⏳ Texture Exploration (8 min) — Today');
      buf.writeln('✓ Block Stacking (10 min) — Yesterday');
      buf.writeln('— Emotion Matching (skipped) — Yesterday');
      buf.writeln('✓ Breathing Exercise (5 min) — 2 days ago');
      buf.writeln();

      buf.writeln('━━━ MILESTONES ACHIEVED ━━━━━━━━━━━━━');
      buf.writeln('🗣️ First Word! — 3 days ago (Communication)');
      buf.writeln('🧱 Stacked 5 Blocks — 1 week ago (Motor Skills)');
      buf.writeln('🤝 Shared a Toy — 2 weeks ago (Social Skills)');
      buf.writeln();

      buf.writeln('━━━ OBSERVATIONS ━━━━━━━━━━━━━━━━━━━━');
      buf.writeln('• Child shows strong engagement with visual activities');
      buf.writeln('• Communication practice is progressing steadily');
      buf.writeln('• Sensory tolerance has improved over the past 2 weeks');
      buf.writeln('• Motor skill activities require continued focus');
      buf.writeln();

      buf.writeln('═══════════════════════════════════════');
      buf.writeln('⚠️ DISCLAIMER: This report is generated by');
      buf.writeln('CARE-AI, an AI-powered parenting companion.');
      buf.writeln('It does NOT constitute a medical diagnosis.');
      buf.writeln('Please use this as a supplementary reference');
      buf.writeln('for your healthcare discussions.');
      buf.writeln('═══════════════════════════════════════');

      if (mounted) {
        setState(() {
          _report = buf.toString();
          _isLoading = false;
        });
      }
    } catch (e) {
      if (mounted) {
        setState(() {
          _report = 'Error generating report: $e';
          _isLoading = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;

    return Scaffold(
      appBar: AppBar(
        title: const Text('Doctor Report'),
        actions: [
          if (!_isLoading)
            IconButton(
              onPressed: () {
                Clipboard.setData(ClipboardData(text: _report));
                ScaffoldMessenger.of(context).showSnackBar(
                  const SnackBar(
                    content: Text('Report copied to clipboard! 📋'),
                    backgroundColor: AppColors.success,
                  ),
                );
              },
              icon: const Icon(Icons.copy_rounded, size: 22),
              tooltip: 'Copy Report',
            ),
        ],
      ),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator())
          : SingleChildScrollView(
              padding: const EdgeInsets.all(16),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  // Header card
                  Container(
                    width: double.infinity,
                    padding: const EdgeInsets.all(20),
                    decoration: BoxDecoration(
                      gradient: const LinearGradient(
                        colors: [Color(0xFF0EA5E9), Color(0xFF38BDF8)],
                        begin: Alignment.topLeft,
                        end: Alignment.bottomRight,
                      ),
                      borderRadius: BorderRadius.circular(20),
                      boxShadow: [
                        BoxShadow(
                          color: const Color(0xFF0EA5E9)
                              .withValues(alpha: 0.3),
                          blurRadius: 20,
                          offset: const Offset(0, 8),
                        ),
                      ],
                    ),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const Row(
                          children: [
                            Icon(Icons.medical_information_rounded,
                                color: Colors.white, size: 24),
                            SizedBox(width: 10),
                            Text(
                              'Healthcare Provider Report',
                              style: TextStyle(
                                color: Colors.white,
                                fontSize: 18,
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                          ],
                        ),
                        const SizedBox(height: 8),
                        Text(
                          _childName != null
                              ? 'Generated for ${_childName!}'
                              : 'Generated from CARE-AI data',
                          style: TextStyle(
                            color: Colors.white.withValues(alpha: 0.9),
                            fontSize: 13,
                          ),
                        ),
                      ],
                    ),
                  ).animate().fadeIn(duration: 500.ms),

                  const SizedBox(height: 20),

                  // Report content
                  Container(
                    width: double.infinity,
                    padding: const EdgeInsets.all(16),
                    decoration: BoxDecoration(
                      color: isDark
                          ? AppColors.darkCardBackground
                          : AppColors.cardBackground,
                      borderRadius: BorderRadius.circular(16),
                      border: isDark
                          ? Border.all(
                              color: AppColors.darkBorder
                                  .withValues(alpha: 0.3))
                          : null,
                    ),
                    child: SelectableText(
                      _report,
                      style: TextStyle(
                        fontFamily: 'monospace',
                        fontSize: 12,
                        height: 1.5,
                        color: isDark
                            ? AppColors.darkTextPrimary
                            : AppColors.textPrimary,
                      ),
                    ),
                  ).animate().fadeIn(delay: 200.ms, duration: 500.ms),

                  const SizedBox(height: 20),

                  // Copy button
                  SizedBox(
                    width: double.infinity,
                    child: ElevatedButton.icon(
                      onPressed: () {
                        Clipboard.setData(ClipboardData(text: _report));
                        ScaffoldMessenger.of(context).showSnackBar(
                          const SnackBar(
                            content: Text(
                                'Report copied! Share it with your healthcare provider 📋'),
                            backgroundColor: AppColors.success,
                          ),
                        );
                      },
                      icon: const Icon(Icons.share_rounded),
                      label: const Text('Copy & Share with Doctor'),
                      style: ElevatedButton.styleFrom(
                        backgroundColor: const Color(0xFF0EA5E9),
                        foregroundColor: Colors.white,
                        padding: const EdgeInsets.symmetric(vertical: 16),
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(14),
                        ),
                        elevation: 0,
                      ),
                    ),
                  ).animate().fadeIn(delay: 400.ms, duration: 500.ms),
                ],
              ),
            ),
    );
  }
}
